import type { PageBuilderDocument, PageBuilderSection, ProductShowcaseSection } from "./schema";
import { sectionLabels } from "./sections";
import { evaluatePageBuilderReadiness, readinessToMarkdown } from "./readiness";

function list(items: string[]): string {
  if (items.length === 0) return "- None";
  return items.map((item) => `- ${item}`).join("\n");
}

export function productShowcaseToMarkdown(section: ProductShowcaseSection): string {
  const ctas =
    section.ctas.length === 0
      ? "- None"
      : section.ctas
          .map((cta) => `- ${cta.label} (${cta.variant}${cta.href ? ` -> ${cta.href}` : ""})`)
          .join("\n");

  const features =
    section.features.length === 0
      ? "- None"
      : section.features
          .map((feature) => {
            const value = `${feature.value}${feature.unit ? ` ${feature.unit}` : ""}`;
            const description = feature.description ? ` — ${feature.description}` : "";
            return `- ${feature.label}: ${value}${description}`;
          })
          .join("\n");

  const theme = [
    `Background: ${section.theme.background}`,
    `Foreground: ${section.theme.foreground}`,
    `Muted: ${section.theme.muted}`,
    `Accent: ${section.theme.accent}`,
    `Card: ${section.theme.card}`,
    `Border: ${section.theme.border}`,
    `Overlay gradient: ${section.theme.overlayGradient}`,
  ].join("\n");

  const hasAsset = section.productAsset.src.trim().length > 0;
  const assetStatus = hasAsset
    ? `Provided: ${section.productAsset.src}${section.productAsset.type ? ` (${section.productAsset.type})` : ""}`
    : "MISSING ASSET — product asset src is empty (draft)";

  return [
    "## Product Showcase",
    "",
    `Product name: ${section.productName}`,
    `Layout: ${section.layout}`,
    section.eyebrow ? `Eyebrow: ${section.eyebrow}` : "",
    `Headline: ${section.headline}`,
    section.subheadline ? `Subheadline: ${section.subheadline}` : "",
    section.specText ? `Spec text: ${section.specText}` : "",
    section.mediaPosition ? `Media position: ${section.mediaPosition}` : "",
    "",
    "CTAs:",
    ctas,
    "",
    "Feature cards:",
    features,
    "",
    "Theme:",
    theme,
    "",
    "Product asset status:",
    `- ${assetStatus}`,
    `- Alt text: ${section.productAlt}`,
    "",
    "Implementation notes:",
    `- Render this section in ${section.layout} layout, theme-driven from the tokens above.`,
    `- Motion: ${section.motion?.enabled ? "enabled" : "disabled"} (parallax: ${section.motion?.productParallax ?? "none"}, reveal: ${section.motion?.featureReveal ?? "none"}).`,
    "- No UI is generated by the core; this is a contract for a downstream renderer.",
    "",
    "Asset requirements:",
    `- Product asset (${section.productAlt}) at ${section.productAsset.width ?? "?"}x${section.productAsset.height ?? "?"}.`,
    hasAsset ? "- Asset source present." : "- Asset source required before export_ready.",
  ]
    .filter((part) => part !== "")
    .join("\n");
}

function sectionToMarkdown(section: PageBuilderSection): string {
  switch (section.type) {
    case "hero":
      return [
        "## Hero",
        "",
        `Headline: ${section.headline}`,
        section.subheadline ? `Subheadline: ${section.subheadline}` : "",
        `Primary CTA: ${section.primary_cta}`,
        section.secondary_cta ? `Secondary CTA: ${section.secondary_cta}` : "",
        section.proof_line ? `Proof line: ${section.proof_line}` : "",
      ].filter(Boolean).join("\n");
    case "problem":
      return [
        "## Problem",
        "",
        `Title: ${section.title}`,
        "",
        "Symptoms:",
        list(section.symptoms),
        "",
        `Cost of inaction: ${section.cost_of_inaction}`,
      ].join("\n");
    case "mechanism":
      return [
        "## Mechanism",
        "",
        `Title: ${section.title}`,
        `Explanation: ${section.explanation}`,
        `Why it works: ${section.why_it_works}`,
        "",
        "Difference from alternatives:",
        list(section.difference_from_alternatives),
      ].join("\n");
    case "offer":
      return [
        "## Offer",
        "",
        `Title: ${section.title}`,
        "",
        "Deliverables:",
        list(section.deliverables),
        "",
        `Format: ${section.format}`,
        `Timeline: ${section.timeline}`,
      ].join("\n");
    case "proof":
      return [
        "## Proof",
        "",
        "Proof points:",
        list(section.proof_points),
        "",
        "Credibility signals:",
        list(section.credibility_signals),
        "",
        "Testimonial placeholders:",
        list(section.testimonial_placeholders),
      ].join("\n");
    case "pricing":
      return [
        "## Pricing",
        "",
        `Pilot price: ${section.pilot_price}`,
        `Premium upgrade: ${section.premium_upgrade}`,
        `Pricing rationale: ${section.pricing_rationale}`,
        `Risk reversal: ${section.risk_reversal}`,
      ].join("\n");
    case "faq":
      return [
        "## FAQ",
        "",
        section.items.map((item) => `### ${item.question}\n${item.answer}`).join("\n\n"),
      ].join("\n");
    case "final_cta":
      return [
        "## Final CTA",
        "",
        `Headline: ${section.headline}`,
        `CTA: ${section.cta}`,
        section.microcopy ? `Microcopy: ${section.microcopy}` : "",
      ].filter(Boolean).join("\n");
    case "implementation_notes":
      return [
        "## Implementation Notes",
        "",
        "Component hierarchy:",
        list(section.components),
        "",
        "Required sections:",
        list(section.required_sections.map((type) => sectionLabels[type])),
        "",
        "Missing visual assets:",
        list(section.missing_visual_assets),
        "",
        "Acceptance checks:",
        list(section.acceptance_checks),
      ].join("\n");
    case "navigation_bar":
      return [
        "## Navigation Bar",
        "",
        `Logo: ${section.logo_label}`,
        "",
        "Links:",
        list(section.links.map((link) => `${link.label} -> #${link.anchor}`)),
        section.cta ? `\nCTA: ${section.cta.label}` : "",
      ].filter(Boolean).join("\n");
    case "footer":
      return [
        "## Footer",
        "",
        section.tagline ? `Tagline: ${section.tagline}` : "",
        "",
        "Link groups:",
        section.link_groups
          .map((group) => `### ${group.heading}\n${list(group.links.map((link) => link.label))}`)
          .join("\n\n"),
        section.legal ? `\nLegal: ${section.legal}` : "",
      ].filter(Boolean).join("\n");
    case "testimonials":
      return [
        "## Testimonials",
        "",
        section.title ? `Title: ${section.title}` : "",
        "",
        section.items.map((item) => `> ${item.quote}\n> — ${item.author}${item.role ? `, ${item.role}` : ""}`).join("\n\n"),
      ].filter(Boolean).join("\n");
    case "logo_strip":
      return [
        "## Logo Strip",
        "",
        section.title ? `Title: ${section.title}` : "",
        "",
        "Logos:",
        list(section.logos.map((logo) => logo.name)),
      ].filter(Boolean).join("\n");
    case "stats_bar":
      return [
        "## Stats Bar",
        "",
        section.title ? `Title: ${section.title}` : "",
        "",
        "Stats:",
        list(section.stats.map((stat) => `${stat.value} — ${stat.label}`)),
      ].filter(Boolean).join("\n");
    case "feature_split":
      return [
        "## Feature Split",
        "",
        `Title: ${section.title}`,
        section.description ? `Description: ${section.description}` : "",
        "",
        "Features:",
        list(section.features.map((feature) => (feature.description ? `${feature.title}: ${feature.description}` : feature.title))),
      ].filter(Boolean).join("\n");
    case "product_showcase":
      return productShowcaseToMarkdown(section);
  }
}

export function pageBuilderDocumentToMarkdown(document: PageBuilderDocument): string {
  const sectionOrder = document.sections.map((section) => section.type).join(" -> ");
  const brandContext = document.brand_context
    ? [
        `Brand slug: ${document.brand_context.slug ?? "n/a"}`,
        `Dominant mechanism: ${document.brand_context.dominant_mechanism ?? "n/a"}`,
        `Applied mechanism: ${document.brand_context.applied_mechanism ?? "n/a"}`,
        `Task type: ${document.brand_context.task_type ?? "n/a"}`,
      ].join("\n")
    : "Brand context: n/a";

  return [
    `# ${document.title}`,
    "",
    `Page type: ${document.page_type}`,
    `Schema version: ${document.schema_version ?? "1.0.0"}`,
    `Status: ${document.status}`,
    document.source ? `Source: ${document.source}` : "",
    "",
    "## Meta",
    "",
    brandContext,
    "",
    "## Section Order",
    "",
    sectionOrder,
    "",
    ...document.sections.map(sectionToMarkdown),
    "",
    readinessToMarkdown(evaluatePageBuilderReadiness(document)),
  ].filter((part) => part !== "").join("\n\n");
}
