import Link from "next/link";

const panels = [
  "Offer",
  "Copy",
  "UX audit",
  "Component plan",
  "Motion plan",
  "Visual brief",
  "Build plan",
  "Launch plan"
];

export default function OutputPreviewPage() {
  return (
    <main className="mx-auto max-w-7xl px-5 py-10">
      <div className="mb-8 flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="font-mono text-xs font-black uppercase tracking-[0.18em] text-violet-400">Output Preview</p>
          <h1 className="mt-2 text-3xl font-black tracking-[-0.04em] text-white md:text-4xl">
            Asset panels generated by Prompt Studio.
          </h1>
        </div>
        <Link
          className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white shadow-[0_0_20px_rgba(124,58,237,0.35)] transition hover:-translate-y-0.5 hover:bg-violet-500"
          href="/new-project"
        >
          Generate new output
        </Link>
      </div>
      <section className="grid gap-3 md:grid-cols-2">
        {panels.map((panel) => (
          <article
            className="rounded-2xl border border-white/[0.07] bg-white/[0.03] p-5 transition duration-200 hover:border-violet-500/15 hover:bg-white/[0.04]"
            key={panel}
          >
            <p className="font-mono text-xs font-black uppercase tracking-[0.16em] text-violet-400">{panel}</p>
            <p className="mt-3 text-sm leading-7 text-white/40">
              This panel is generated locally from EMOVEL skill markdown, production pipeline templates, and project template rules.
            </p>
          </article>
        ))}
      </section>
    </main>
  );
}
