import Link from "next/link";

const panels = [
  "Offer",
  "Copy",
  "UX audit",
  "Component plan",
  "Motion plan",
  "Visual brief",
  "Build plan",
  "Launch plan"
];

export default function OutputPreviewPage() {
  return (
    <main className="mx-auto max-w-7xl px-5 py-10">
      <div className="mb-8 flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="font-mono text-xs font-black uppercase tracking-[0.18em] text-blue">Output Preview</p>
          <h1 className="mt-2 text-4xl font-black tracking-[-0.04em]">Asset panels generated by Prompt Studio.</h1>
        </div>
        <Link className="rounded-emovel bg-blue px-5 py-3 font-black text-white" href="/new-project">
          Generate new output
        </Link>
      </div>
      <section className="grid gap-3 md:grid-cols-2">
        {panels.map((panel) => (
          <article className="rounded-emovel border border-line bg-white p-5" key={panel}>
            <p className="font-mono text-xs font-black uppercase tracking-[0.16em] text-blue">{panel}</p>
            <p className="mt-3 leading-7 text-slate-600">
              This panel is generated locally from EMOVEL skill markdown, production pipeline templates, and project template rules.
            </p>
          </article>
        ))}
      </section>
    </main>
  );
}
